Repository SAP/neonbee, pull requests merged in 2022-08, with the labels that each got.

#141 docs(health): add documentation for the health feature
  .gitattributes
  docs/health-checks.drawio
  docs/health-checks.png
  docs/health.md
Labels: documentation

#144 feat: Make ServerVerticle handler configurable.
  docs/ServerVerticle.md
  resources/config/io.neonbee.internal.verticle.ServerVerticle.example.yaml
  src/generated/java/io/neonbee/config/ServerConfigConverter.java
  src/main/java/io/neonbee/config/ServerConfig.java
  src/main/java/io/neonbee/internal/handler/factories/CacheControlHandlerFactory.java
  src/main/java/io/neonbee/internal/handler/factories/CorrelationIdHandlerFactory.java
  src/main/java/io/neonbee/internal/handler/factories/DisallowingFileUploadBodyHandlerFactory.java
  src/main/java/io/neonbee/internal/handler/factories/InstanceInfoHandlerFactory.java
  src/main/java/io/neonbee/internal/handler/factories/LoggerHandlerFactory.java
  src/main/java/io/neonbee/internal/handler/factories/RoutingHandlerFactory.java
  src/main/java/io/neonbee/internal/handler/factories/SessionHandlerFactory.java
  src/main/java/io/neonbee/internal/handler/factories/TimeoutHandlerFactory.java
  src/main/java/io/neonbee/internal/verticle/ServerVerticle.java
  src/test/java/io/neonbee/config/ServerConfigTest.java
  src/test/java/io/neonbee/internal/handler/factories/CacheControlHandlerFactoryTest.java
  src/test/java/io/neonbee/internal/handler/factories/CorrelationIdHandlerFactoryTest.java
  src/test/java/io/neonbee/internal/handler/factories/DisallowingFileUploadBodyHandlerFactoryTest.java
  src/test/java/io/neonbee/internal/handler/factories/InstanceInfoHandlerFactoryTest.java
  src/test/java/io/neonbee/internal/handler/factories/LoggerHandlerFactoryTest.java
  src/test/java/io/neonbee/internal/handler/factories/SessionHandlerFactoryTest.java
  src/test/java/io/neonbee/internal/handler/factories/TimeoutHandlerFactoryTest.java
  src/test/java/io/neonbee/internal/verticle/ServerVerticleTest.java
Labels: code review required, additional documentation required

#142 feat: support response hint
  src/main/java/io/neonbee/data/DataContext.java
  src/main/java/io/neonbee/data/DataVerticle.java
  src/main/java/io/neonbee/data/internal/DataContextImpl.java
  src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/CountEntityCollectionProcessor.java
  src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/ProcessorHelper.java
  src/main/java/io/neonbee/endpoint/raw/RawEndpoint.java
  src/main/java/io/neonbee/internal/helper/CollectionHelper.java
  src/test/java/io/neonbee/data/internal/DataContextImplTest.java
  src/test/java/io/neonbee/data/internal/ResponseMetadataIntegrationTest.java
  src/test/java/io/neonbee/endpoint/odatav4/ODataV4EndpointTest.java
  src/test/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/ProcessorHelperTest.java
Labels: code review required, concept validation required, additional documentation required
